### ISSUE TITLE
Why not shellHistory.path?

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/shell-history#2]
In the readme I see

```js
console.log(shellHistory().path);
```

Does that not first enumerate the entire history (`shellHistory()`, a potentially lengthy operation) and then get the `.path` property from the result?

Why not compute the path to the history first and story it on the `module.exports` itself, allowing one to do

```js
console.log(shellHistory.path);
```

**Comment by sindresorhus** [comment]
The algorithm works by finding all possible history files, read them, convert to array and check which ones has the the most commands (note that this is different from the file size). So it has to do everything before knowing the path, so made more sense to put it on the result array. Happy to receive suggestions for an improved algorithm for this, though.

**Comment by Qix-** [comment]
Hmm. Which results are you returning as far as commands? Do you just discard the history files that have a lesser number of commands and only return the one with the most?

**Comment by sindresorhus** [comment]
> Do you just discard the history files that have a lesser number of commands and only return the one with the most?

Yes

**Comment by Qix-** [comment]
Hmm. What's the goal of this module? I would imagine it's goal is to have the history of the user's actual shell. What other kinds of places is history being pulled from?

**Comment by sindresorhus** [comment]
> What's the goal of this module?

The goal is to get the history of the user's main shell.

> What other kinds of places is history being pulled from?

What do you mean?

**Comment by Qix-** [comment]
Well realistically, on POSIX shells, `$HISTFILE` should specify where it's at. That should be enough.

**Comment by sindresorhus** [comment]
"Should" when dealing with computers usually means "one in a while" :p

For example, `$HISTFILE` is not defined by default in ZSH. Fish shell probably uses something different.

**Comment by Qix-** [comment]
Regardless, though, shells are only putting history in one file. It isn't necessarily correct to assert the longest one to be the correct history file.

**Comment by sindresorhus** [comment]
Ok, how about trying `$HISTFILE` first, if not defined or not found, try the current strategy?

**Comment by Qix-** [comment]
Yeah, probably safest. At least that gives the user the ability to fix the mistake of this module is acting up.
