### ISSUE TITLE
.zsh_history file not found

### ISSUE THREAD

**Issue by dawsonbotsford** [sindresorhus/shell-history#3]
Here's the error:

```sh
str.trim.split.map.Array.from.map.fp.reduce.module.exports.opts (node_modules/shell-history/index.js:60:18)
    module.exports (index.js:6:15)
```

This code caused it:
```js
'use strict';

const shellHistory = require('shell-history');

module.exports = function (replaceMe) {
  console.log(shellHistory());
  return replaceMe;
};
```

Isolating the issue to just the `getPath` function:
```sh
node
> const h = require('shell-history')
undefined
> h.path()
undefined
```

I have an expected and non-empty `.zsh_history` location:

```sh
> os.homedir()
'/Users/dawsonbotsford'
```

```sh
 ~  cat /Users/dawsonbotsford/.zsh_history
: 1483040067:0;ls
: 1483040067:0;rm -rf .zsh
: 1483040067:0;ls
: 1483040067:0;rm .zsh*
...
```

---

[sist](https://github.com/dawsonbotsford/sist) output:

### node  
`npm -v`: 2.15.11
`node --version`: v4.7.0

### shell  
`uname`: Darwin
`echo $SHELL`: /bin/zsh
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: iTerm.app

Time created: Sun Jan 15 2017 18:15:54 GMT-0800 (PST)

**Comment by dawsonbotsford** [comment]
Bump

**Comment by sindresorhus** [comment]
> Here's the error:

> str.trim.split.map.Array.from.map.fp.reduce.module.exports.opts (node_modules/shell-history/index.js:60:18)
    module.exports (index.js:6:15)

Can you share the full error? I don't see any error message there or the full stack.

**Comment by dawsonbotsford** [comment]
Attempted to recreate the error in order to paste a full stack trace and everything is working. Sorry to bother, will re-open if the issue persists.
